export const Teachers = [
  {
    key: "1",
    name: "Teacher A",
    id: "KEY01",
    email: "teacher@gmail.com",
    phone: "0905 123 123",
    status: "Active",
  },
  {
    key: "2",
    name: "Teacher B",
    id: "KEY02",
    email: "teacherB@gmail.com",
    phone: "0905 456 789",
    status: "Active",
  },
  {
    key: "3",
    name: "Teacher C",
    id: "KEY03",
    email: "teacherC@gmail.com",
    phone: "0905 222 333",
    status: "Deactivate",
  },
  {
    key: "4",
    name: "Teacher D",
    id: "KEY04",
    email: "teacherD@gmail.com",
    phone: "0905 333 444",
    status: "Active",
  },
  {
    key: "5",
    name: "Teacher E",
    id: "KEY05",
    email: "teacherE@gmail.com",
    phone: "0905 555 666",
    status: "Deactivate",
  },
  {
    key: "6",
    name: "Teacher F",
    id: "KEY06",
    email: "teacherF@gmail.com",
    phone: "0905 777 888",
    status: "Active",
  },
  {
    key: "7",
    name: "Teacher G",
    id: "KEY07",
    email: "teacherG@gmail.com",
    phone: "0905 999 000",
    status: "Deactivate",
  },
  {
    key: "8",
    name: "Teacher H",
    id: "KEY08",
    email: "teacherH@gmail.com",
    phone: "0905 111 222",
    status: "Active",
  },
  {
    key: "9",
    name: "Teacher I",
    id: "KEY09",
    email: "teacherI@gmail.com",
    phone: "0905 333 555",
    status: "Active",
  },
  {
    key: "10",
    name: "Teacher J",
    id: "KEY10",
    email: "teacherJ@gmail.com",
    phone: "0905 444 666",
    status: "Deactivate",
  },
  {
    key: "11",
    name: "Teacher K",
    id: "KEY11",
    email: "teacherK@gmail.com",
    phone: "0905 555 777",
    status: "Active",
  },
  {
    key: "12",
    name: "Teacher L",
    id: "KEY12",
    email: "teacherL@gmail.com",
    phone: "0905 666 888",
    status: "Deactivate",
  },
  {
    key: "13",
    name: "Teacher M",
    id: "KEY13",
    email: "teacherM@gmail.com",
    phone: "0905 777 999",
    status: "Active",
  },
  {
    key: "14",
    name: "Teacher N",
    id: "KEY14",
    email: "teacherN@gmail.com",
    phone: "0905 888 000",
    status: "Active",
  },
  {
    key: "15",
    name: "Teacher O",
    id: "KEY15",
    email: "teacherO@gmail.com",
    phone: "0905 999 111",
    status: "Deactivate",
  },
  {
    key: "16",
    name: "Teacher P",
    id: "KEY16",
    email: "teacherP@gmail.com",
    phone: "0905 222 444",
    status: "Active",
  },
  {
    key: "17",
    name: "Teacher Q",
    id: "KEY17",
    email: "teacherQ@gmail.com",
    phone: "0905 333 666",
    status: "Active",
  },
  {
    key: "18",
    name: "Teacher R",
    id: "KEY18",
    email: "teacherR@gmail.com",
    phone: "0905 444 777",
    status: "Deactivate",
  },
  {
    key: "19",
    name: "Teacher S",
    id: "KEY19",
    email: "teacherS@gmail.com",
    phone: "0905 555 888",
    status: "Active",
  },
  {
    key: "20",
    name: "Teacher T",
    id: "KEY20",
    email: "teacherT@gmail.com",
    phone: "0905 666 999",
    status: "Deactivate",
  },
];
